/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "SAHek_b4lGY",
    title: "Black Pepper Farming",
    categoryName: "Others",
    creator: "Discover Agriculture",
    views: 787887,
    date: "29 May 2021",
    likes: 2766,
    videoThumbnail: "https://i.postimg.cc/dtzT3h0N/others-3.png",
    url: "https://youtu.be/SAHek_b4lGY",
    description:
      "Black pepper is one of the popular spices and known as the “king of spices”. This spice was originated from Western Ghats of India.",
  },
  {
    _id: "va14fRzCZSw",
    title: "Fish Farming in artificial pond",
    categoryName: "Fish Farming",
    creator: "Organic Acre",
    views: 45343,
    date: "1 Mar 2021",
    likes: 34453,
    videoThumbnail: "https://i.postimg.cc/v8tPWdnv/fish-2.png",
    url: "https://youtu.be/va14fRzCZSw",
    description:
      "Multi-layer fish farming by leaving high paying job in germany",
  },
  {
    _id: "je9mh5jtTH8",
    title: "High-Tech Poultry Farm",
    categoryName: "Poultry Farming",
    creator: "Science & Technology UI",
    views: 643545,
    date: "14 Aug 2021",
    likes: 67676,
    videoThumbnail: "https://i.postimg.cc/Njq5YZNW/poultry-1.png",
    url: "https://youtu.be/je9mh5jtTH8",
    description:
      "Amazing High-Tech Poultry Farm Produce more than 260 million Chickens a year, 1.5 million eggs daily.",
  },
  {
    _id: "nQAxf_C3MGU",
    title: "Tilapia Fish Farming",
    categoryName: "Fish Farming",
    creator: "My Click Support",
    views: 23453,
    date: "1 Feb 2021",
    likes: 23453,
    videoThumbnail: "https://i.postimg.cc/cL2Ts1qd/fish-1.png",
    url: "https://youtu.be/nQAxf_C3MGU",
    description:
      "Tilapia is tolerant of a variety of aquaculture environments, it can be farmed in brackish or salt water and also in pond or cage systems. ",
  },
  {
    _id: "FyOzeO6fQwI",
    title: "Multilayer Farming to earn more",
    categoryName: "Vegetable Farming",
    creator: "Down To Earth",
    views: 655655,
    date: "6 May 2021",
    likes: 5655,
    videoThumbnail: "https://i.postimg.cc/Qtydzz9Y/vegetable-2.png",
    url: "https://youtu.be/FyOzeO6fQwI",
    description:
      "Akash Chaurasia is a marginal farmer from Bundelkhand, Madhya Pradesh. With low cost and innovative farming technique",
  },
  {
    _id: "WT6WJZK8VWY",
    title: "Best Integrated Farm in the World",
    categoryName: "Others",
    creator: "Discover Agriculture",
    views: 544433,
    date: "1 May 2021",
    likes: 66565,
    videoThumbnail: "https://i.postimg.cc/4NK9X6Xh/others-1.png",
    url: "https://youtu.be/WT6WJZK8VWY",
    description:
      "The integrated farming system is a commonly used term to explain a more integrated approach to farming compared to monoculture approaches.",
  },
  {
    _id: "FnJzxWu22RQ",
    title: "Gowri Fish Farming",
    categoryName: "Fish Farming",
    creator: "IndiaMoney.com",
    views: 43545,
    date: "16 Feb 2022",
    likes: 78676,
    videoThumbnail: "https://i.postimg.cc/j5rX78d9/fish-3.png",
    url: "https://youtu.be/1IwKWYNycj8",
    description: "Gowri Fish farming course by IndiaMoney.com in Kannada",
  },
  {
    _id: "JcG3-g6UH90",
    title: "Largest Poultry Farm",
    categoryName: "Poultry Farming",
    creator: "GAURAV ZONE",
    views: 52225,
    date: "20 Aug 2020",
    likes: 2232,
    videoThumbnail: "https://i.postimg.cc/TPT15gv0/poultry-2.png",
    url: "https://youtu.be/JcG3-g6UH90",
    description:
      "Visited india's largest poultry farm and explained poultry system they are following.",
  },
  {
    _id: "Zlzll-8DanU",
    title: "Organic Farming in Kannada",
    categoryName: "Vegetable Farming",
    creator: "Krishi Nudi",
    views: 43454,
    date: "25 Jul 2021",
    likes: 6555,
    videoThumbnail: "https://i.postimg.cc/bvLJxrzh/vegetable-3.png",
    url: "https://youtu.be/Zlzll-8DanU",
    description:
      "Explained how to earn nearly 1 lakh per month by growing 16 varieties in 5 acre of land",
  },
  {
    _id: "fShMEWv3Br8",
    title: "Farmer's success story in integrated Farming",
    categoryName: "Others",
    creator: "Discover Agriculture",
    views: 55454,
    date: "23 Sept 2020",
    likes: 44433,
    videoThumbnail: "https://i.postimg.cc/sfHWF6Cr/others-2.png",
    url: "https://youtu.be/fShMEWv3Br8",
    description:
      "Integrated Farming System developed by farmer Shri Dheeraj Singh and demonstrated by KVK Kaushambi under ICAR-ATARI, Kanpur",
  },
  {
    _id: "ZuzZXT3A1aQ",
    title: "Pomogranate cultivation using modern technology",
    categoryName: "Fruit Farming",
    creator: "Noal Farm",
    views: 345343,
    date: "29 Jan 2020",
    likes: 64565,
    videoThumbnail: "https://i.postimg.cc/13ncYx82/fruit-1.png",
    url: "https://youtu.be/ZuzZXT3A1aQ",
    description:
      "Showing awesome agriculture technology for Pomegranate cultivation - Pomegranate Farm and Harvest",
  },
  {
    _id: "nccV__8Pb9U",
    title: "Simple farming methods",
    categoryName: "Vegetable Farming",
    creator: "The One Page",
    views: 56767,
    date: "12 Feb 2021",
    likes: 6767,
    videoThumbnail: "https://i.postimg.cc/V66NDw6b/vegetable-1.png",
    url: "https://youtu.be/nccV__8Pb9U",
    description:
      "Easiest way to grow Top 8 Vegetables at Home/Garden | small space gardening, kitchen garden at home",
  },
  {
    _id: "pDesLJVo0XI",
    title: "Modern Fish Farm",
    categoryName: "Fish Farming",
    creator: "NaLac Technique",
    views: 5552,
    date: "20 Oct 2021",
    likes: 65656,
    videoThumbnail: "https://i.postimg.cc/9f9bz3VZ/fish-4.png",
    url: "https://youtu.be/pDesLJVo0XI",
    description:
      "Modern Fish Farm with Amazing Technology and Cool Machines for The Highest Productivity.",
  },
  {
    _id: "LlGHHueBVVg",
    title: "Information of Broiler poultry farming",
    categoryName: "Poultry Farming",
    creator: "How to Start?",
    views: 63352,
    date: "10 May 2019",
    likes: 5565,
    videoThumbnail: "https://i.postimg.cc/T3VhPQFh/poultry-3.png",
    url: "https://youtu.be/LlGHHueBVVg",
    description:
      "This video provides complete information about broiler poultry farming along with marketing techniques and many more about farming ",
  },
  {
    _id: "1IZ1VtjutfI",
    title: "Taiwan Guava fruit Harvesting",
    categoryName: "Fruit Farming",
    creator: "Villege Vlogs",
    views: 67453,
    date: "20 Apr 2021",
    likes: 10453,
    videoThumbnail: "https://i.postimg.cc/HLb0dQ4t/fruit-3.png",
    url: "https://youtu.be/1IZ1VtjutfI",
    description:
      "Prvides complete information about Taiwan Guava Farming, Cultivation, Harvesting and yield information",
  },
  {
    _id: "HCgWrtf2xFM",
    title: "Walkthrough of 150 Murrah Buffalo Dairy Farm",
    categoryName: "Dairy Farming",
    creator: "Farmer's Market",
    views: 67567,
    date: "25 Jan 2021",
    likes: 7656,
    videoThumbnail: "https://i.postimg.cc/Bb4MdmrD/dairy-1.png",
    url: "https://youtu.be/HCgWrtf2xFM",
    description:
      "Watch how a 150 Murrah buffalo farm is managed by a team from Haryana in Karnataka. This team hand milks 300 liters of milk per time and the milk is sold at 60 rupees per liter.",
  },
  {
    _id: "vy-OTRXZ7Lw",
    title: "Avacado Fruit Farming",
    categoryName: "Fruit Farming",
    creator: "Vijaya Karnataka",
    views: 453453,
    date: "19 Oct 2021",
    likes: 23453,
    videoThumbnail: "https://i.postimg.cc/13k0kW6t/fruit-2.png",
    url: "https://youtu.be/vy-OTRXZ7Lw",
    description:
      "Provides complete information required to do avacado fruit farming, which is entering market with good impression",
  },
  {
    _id: "UDFikPGIkAc",
    title: "Modern Dary farm in Punjab",
    categoryName: "Dairy Farming",
    creator: "Gurkirpal Singh",
    views: 45664,
    date: "7 Feb 2020",
    likes: 2564,
    videoThumbnail: "https://i.postimg.cc/XJwsHRz4/dairy-2.png",
    url: "https://youtu.be/UDFikPGIkAc",
    description:
      "In this video we have covered Tour of Modern Dairy Farm of India the name of farm is Gill Dairy Farm Moga Punjab. Here holstein friesian cows (hf cow) giving up to 60 liter milk per day are present.",
  },
  {
    _id: "-1IVpmYqFfQ",
    title: "Agro Forestry, Tree based Farming",
    categoryName: "Forestry Farming",
    creator: "Isha Foundation",
    views: 645454,
    date: "23 July 2018",
    likes: 65444,
    videoThumbnail: "https://i.postimg.cc/QCfkvhkG/forest-1.png",
    url: "https://youtu.be/-1IVpmYqFfQ",
    description:
      "Through our agro-forestry initiative Trees for Life, we support farmers to plant ecologically beneficial trees on their lands.",
  },
  {
    _id: "RXrOlWsYSec",
    title: "Organic Clove Harvesting",
    categoryName: "Others",
    creator: "Picment Studio",
    views: 64544,
    date: "19 Apr 2020",
    likes: 54544,
    videoThumbnail: "https://i.postimg.cc/zvQHnBFB/others-4.png",
    url: "https://youtu.be/RXrOlWsYSec",
    description:
      "This video provides complete information about how clove farming and harvesting happens in idukki kerala",
  },
  {
    _id: "iO0ycMkr8lo",
    title: "Introduction to Agroforestry",
    categoryName: "Forestry Farming",
    creator: "Regenerative Films",
    views: 443444,
    date: "1 Jan 2022",
    likes: 54433,
    videoThumbnail: "https://i.postimg.cc/3JbFBrx2/forest-3.png",
    url: "https://youtu.be/iO0ycMkr8lo",
    description:
      "In this video, we visit James from@Tap o' Noth Permaculture - a food forest farm in Aberdeenshire, Scotland.",
  },
  {
    _id: "p_rtdPtdmAU",
    title: "Modern Cow Dairy Farming",
    categoryName: "Dairy Farming",
    creator: "Noal Farm",
    views: 664564,
    date: "17 Aug 2020",
    likes: 56554,
    videoThumbnail: "https://i.postimg.cc/RhdX9cmY/dairy-3.png",
    url: "https://youtu.be/p_rtdPtdmAU",
    description:
      "This video shows modern cow dairy farming, cow milking technology machine in one of the modern dairy farm",
  },
  {
    _id: "0FcqBJeZ0B4",
    title: "What is Forestry Farming?",
    categoryName: "Forestry Farming",
    creator: "Forest Farming",
    views: 565565,
    date: "28 Sept 2017",
    likes: 65655,
    videoThumbnail: "https://i.postimg.cc/3r1BkFMS/forest-2.png",
    url: "https://youtu.be/0FcqBJeZ0B4",
    description:
      "This video provides complete information about what is forest farming?",
  },
  {
    _id: "8glQBpmFLOw",
    title: "Coconut farming and harvesting",
    categoryName: "Others",
    creator: "Noal Farm",
    views: 565534,
    date: "18 Aug 2019",
    likes: 655544,
    videoThumbnail: "https://i.postimg.cc/cJWg7PwQ/others-5.png",
    url: "https://youtu.be/8glQBpmFLOw",
    description:
      "The coconut palm is the most useful palm in the world. Every part of the tree is useful to human life for some purpose or the other.",
  },
  // {
  //   _id: uuid(),
  //   title: "Hydroponic Strawberries Farming",
  //   categoryName: "Others",
  //   creator: "Noal Farm",
  //   videoThumbnail:"https://i.postimg.cc/cLwtndgx/others-6.png",
  //   url: "https://youtu.be/1IwKWYNycj8",
  //   description:
  //     "Growing strawberries hydroponically ensures that weather is not a factor, and allows you to harvest them all year long. ",
  // },
];
